CREATE TABLE IF NOT EXISTS user_comments (
    comment_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
        /*REFERENCES us_states(state_id) ON DELETE CASCADE*/,
    state_id INTEGER
        REFERENCES us_states(id) ON DELETE CASCADE NOT NULL,
    author TEXT NOT NULL,
    comment_body TEXT NOT NULL,
    date_posted TIMESTAMPTZ NOT NULL DEFAULT now()
);